#ifndef _AGENT_GENERATOR_DATA_FORMAT_H_
#define _AGENT_GENERATOR_DATA_FORMAT_H_

#define AGENT_GEN_DF_TAG_MAIN					"AGENT_GENERATOR"
#define AGENT_GEN_DF_TAG_OBJ_ID					"AGENT_GEN_ID"
#define AGENT_GEN_DF_TAG_BEGIN					"BEGIN"
#define AGENT_GEN_DF_TAG_AGENT_PATH_INDEX		"AGENT_PATH_INDEX"
#define AGENT_GEN_DF_TAG_GEOMETRY				"GEOMETRY"
#define AGENT_GEN_DF_TAG_GEOMETRY_CIRCLE		"CIRCLE"
#define AGENT_GEN_DF_TAG_POSITION				"POSITION"
#define AGENT_GEN_DF_TAG_RADIUS 				"RADIUS"
#define AGENT_GEN_DF_TAG_PLANE_XZ				"PLANE_XZ"
#define AGENT_GEN_DF_TAG_MAX_GENERATION_TIME	"MAX_GENERATION_TIME"
#define AGENT_GEN_DF_TAG_MAX_AGENT_NUMBER		"MAX_AGENT_NUMBER"

#define AGENT_GEN_DF_TAG_AGENT_SPEED			"AGENT_SPEED"
#define AGENT_GEN_DF_TAG_FREQUENCY				"FREQUENCY"
#define AGENT_GEN_DF_TAG_METHOD					"METHOD"
#define AGENT_GEN_DF_TAG_METHOD_RANDOM			"RANDOM"
//#define AGENT_GEN_DF_TAG_AGENT_DESTINATION		"AGENT_DESTINATION"
#define AGENT_GEN_DF_TAG_END					"END"

#endif
