#ifndef _ENVIRONMENT_DATA_FORMAT_H_
#define _ENVIRONMENT_DATA_FORMAT_H_

#define ENV_DF_TAG_MAIN			"ENVIRONMENT"
#define ENV_DF_TAG_BEGIN		"BEGIN"
#define ENV_DF_TAG_END			"END"
#define ENV_DF_TAG_POSITION		"POSITION"
#define ENV_DF_TAG_TEXTURE		"TEXTURE"
#define ENV_DF_TAG_MAP			"BEGIN_MAP"

#endif

