#ifndef _PATH_MANAGER_DATA_FORMAT_H_
#define _PATH_MANAGER_DATA_FORMAT_H_

#define PATH_MANAGER_DF_TAG_MAIN		"AGENT_PATH"
#define PATH_MANAGER_DF_TAG_BEGIN		"BEGIN"
#define PATH_MANAGER_DF_TAG_END			"END"
#define PATH_MANAGER_DF_TAG_RADIUS		"RADIUS"
#define PATH_MANAGER_DF_TAG_POSITION	"POSITION"

#endif
